apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: hello-world
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - nodePort: 30007
      protocol: TCP
      port: 80
      targetPort: 8080